name: Build and Push Docker Image

on:
  push:
    branches: 
      - main
      - dev

env:
  REGISTRY: meihaiyi
  IMAGE_NAME: blender
  BLENDER_MIRROR_URL: https://mirror.clarkson.edu/blender/release

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        blender_version:
          - { version: "3.4.1", short: "3.4" }
          - { version: "3.5.1", short: "3.5" }
          - { version: "3.6.18", short: "3.6" }
          - { version: "4.0.2", short: "4.0" }
          - { version: "4.1.1", short: "4.1" }
          - { version: "4.2.4", short: "4.2" }
          - { version: "4.3.0", short: "4.3" }
        ubuntu_version: ["20.04", "22.04"]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

    #   - name: Log in to Docker Hub
    #     if: github.event_name != 'pull_request'
    #     uses: docker/login-action@v3
    #     with:
    #       username: ${{ secrets.DOCKERHUB_USERNAME }}
    #       password: ${{ secrets.DOCKERHUB_TOKEN }}

    #   - name: Extract metadata for Docker
    #     id: meta
    #     uses: docker/metadata-action@v5
    #     with:
    #       images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    #       tags: |
    #         type=ref,event=branch
    #         type=ref,event=pr
    #         type=semver,pattern={{version}}
    #         type=semver,pattern={{major}}.{{minor}}

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:blender-${{ matrix.blender_version.short }}-ubuntu-${{ matrix.ubuntu_version }}
          build-args: |
            BLENDER_VERSION=${{ matrix.blender_version.version }}
            UBUNTU_VERSION=${{ matrix.ubuntu_version }}
            BLENDER_MIRROR_URL=${{ env.BLENDER_MIRROR_URL }}
        #   labels: ${{ steps.meta.outputs.labels }}
        #   cache-from: type=gha
        #   cache-to: type=gha,mode=max 

      - name: Run tests
        run: |
          docker run --rm ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:blender-${{ matrix.blender_version.short }}-ubuntu-${{ matrix.ubuntu_version }} /tests/render_eevee.py
          docker run --rm ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:blender-${{ matrix.blender_version.short }}-ubuntu-${{ matrix.ubuntu_version }} /tests/render_cycles.py

    #   - name: Push Docker image
    #     if: success()
    #     uses: docker/build-push-action@v5
    #     with:
    #       context: .
    #       push: true
    #       tags: |
    #         ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:blender-${{ matrix.blender_version.short }}-ubuntu-${{ matrix.ubuntu_version }}
    #       build-args: |
    #         BLENDER_VERSION=${{ matrix.blender_version.version }}
    #         UBUNTU_VERSION=${{ matrix.ubuntu_version }}
    #         BLENDER_MIRROR_URL=${{ env.BLENDER_MIRROR_URL }}
    #       labels: ${{ steps.meta.outputs.labels }}
    #       cache-from: type=gha
    #       cache-to: type=gha,mode=max 